integracion:
    resource: "@integracionBundle/Resources/config/routing.yml"
    prefix:   /integracion

sig:
    resource: "@sigBundle/Resources/config/routing.yml"
    prefix:   /sig

wsBundle:
    resource: "@wsBundle/Resources/config/routing.yml"
    prefix:   /ws

siagBundle:
    resource: "@siagBundle/Resources/config/routing.yml"
    prefix:   /
    
sonata:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
    
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
