wsBundle:
    resource: "@wsBundle/Resources/config/routing.yml"
    prefix:   /ws

siagBundle:
    resource: "@siagBundle/Resources/config/routing.yml"
    prefix:   /


sonata:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
    
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

#--------------------------------------------------------------------------------
#--------------------------------------------------------------------------------
_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
  
