security:
    firewalls:
        frontend:
            pattern: ^/*
            anonymous: ~
            form_login:
                default_target_path: /index/
                always_use_default_target_path: true
        admin:
            pattern: ^/admin*
            anonymous: ~
            form_login:
                default_target_path: /index/
                always_use_default_target_path: true
            
        firewalls_ws:
            pattern: ^/ws*
            anonymous: ~
            form_login: ~
            
    access_control:
        - { path: ^/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/autocomplete, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/seguridad/usuario, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/integracion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sig, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ws, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, roles: [ROLE_USUARIO, ROLE_ADMIN] }

    providers:
        usuarios:
            entity: { class: sigaind\siagBundle\Entity\SysUsuarios, property: updalogin }                        
    encoders:
        sigaind\siagBundle\Entity\SysUsuarios: { algorithm: sha512, iterations: 5000, encode_as_base64: true }